name: Falcon Linter Self-Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: Falcon Linter (Dogfooding)
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && 
      (contains(github.event.comment.body, '/falcon-linter --reviewChanges') || contains(github.event.comment.body, '/falcon-linter --generateSummary')))

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.User_Name }}"
          git config --global user.email "${{ secrets.User_Email }}"

      - name: Determine Command
        id: command
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "command_text=review" >> $GITHUB_OUTPUT
          else
            # For issue_comment events, use the comment body as the command
            echo "command_text=\"${{ github.event.comment.body }}\"" >> $GITHUB_OUTPUT
          fi

      - name: Attempt to Run from Source
        id: run_from_source
        continue-on-error: true
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attempting to run linter from PR source..."
          npm ci
          npm run build
          node dist/index.js --command "${{ steps.command.outputs.command_text }}"

      - name: Fallback to Published Version
        if: steps.run_from_source.outcome == 'failure'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running from source failed. Falling back to latest published version from GitHub."
          npm install -g github:dprakash2101/falcon-linter
          # The CLI is now in the path, and it knows how to get context from the environment
          falcon-linter --command "${{ steps.command.outputs.command_text }}"